In [1]:
import numpy as np
from scipy.optimize import minimize
from scipy.optimize import fsolve
from matplotlib import pyplot as plt
from scipy import stats

In [2]:
#value of info with bargaining?

In [3]:

def nash_obj(x, total, outside, beta=.5):
    e = .0001
    obj = -1*( np.log(np.maximum(x-outside,e))*(1-beta) + np.log(np.maximum(total-x,e))*beta )
    return obj

def solve_nash(total, outside):
    result = minimize(nash_obj, total-outside/2, args=(total, outside),
                     method='Nelder-Mead', options={'disp': False})
    return result.x

solve_nash(10,4)

array([7.])

In [4]:
def info_value(total,outside_min,outside_max,density=None):
    #assume uniformly distributed outside option
    support = []
    steps = 0

    if density is None:
        steps = 10
        density = np.array([1/steps]*steps)
        support = np.linspace(outside_min,outside_max,steps)
    else:
        steps = len(density)
        support = np.linspace(outside_min,outside_max,steps)
    
    #compute the solution with average outcome...
    noinfo_outside = (support*density).sum()
    no_info= solve_nash(total,  noinfo_outside)
    
    info = []
    for outside in support:
        result = solve_nash(total,  outside)
        info.append(result)
        
    info = np.array(info)
    return no_info, (info.reshape(steps,)*density).sum()
    


uniform = info_value(10,3,5)
print(uniform)

normal_steps = 100
normal = stats.norm.pdf(np.linspace(-10,10,normal_steps))*(20/normal_steps)
normal_info = info_value(10,1,5,density=normal)
print(normal_info)

(array([7.]), 6.999991421169705)
(array([6.48499573]), 6.435001076638547)
