In [1]:
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.base.model import GenericLikelihoodModel
import scipy.stats as stats

In [8]:
class norm_loglike(GenericLikelihoodModel):
    
    def __init__(self, *args,ols=False, **kwargs):
        super(norm_loglike,self).__init__(*args,**kwargs)
        self.ols = ols

    def loglikeobs(self, params):
        y = self.endog
        x = self.exog
        mu = params[0]
        sigma = np.abs(params[1])
        pr_y = stats.norm.logpdf( y, loc=mu, scale=sigma )
        return pr_y

mu = 0
sigma = 1
nobs = 1000
true_theta = np.array([mu,sigma]) 
yn = np.random.normal(loc=mu, scale=sigma, size=nobs)


def compute_info_matrix(theta):
    model1_deriv = norm_loglike(yn,np.ones(nobs))
    ll1 = model1_deriv.loglikeobs(theta)
    grad1 =  model1_deriv.score_obs(theta)    
    hess1 = model1_deriv.hessian(theta)

    print(grad1.T.dot(grad1))
    print(-1*hess1)

#variance of the gradient is the same as its hessian?
compute_info_matrix(true_theta)

[[ 960.38429694 -135.89914063]
 [-135.89914063 1887.8490162 ]]
[[1000.00076294  -86.17595673]
 [ -86.17595673 1881.15315247]]


In [16]:
false_theta = np.array([1,1])

compute_info_matrix(false_theta)

[[ 2046.56026578 -3146.31598486]
 [-3146.31598486  7366.10329845]]
[[  999.99999619 -2086.17602921]
 [-2086.17602921  5139.6813736 ]]


In [17]:
false_theta = np.array([0,2])
compute_info_matrix(false_theta)

[[ 60.02401856  -0.20734961]
 [ -0.20734961 173.83661304]]
[[250.00038147 -10.77198029]
 [-10.77198029 -69.92793369]]


In [ ]:
#the hessian measures how "pointy" the top is
#the variance of the score... is how right are the focs?... 

#those things must be equal? in some sense?
#very pointy top... could mean a lot of variance in the focs... over fitting... to some degree...
# very non-pointy top... but not a lot variance in focs... under fitting... to some degree...