In [ ]:
#with misepcificed moments everything depends on the limiting behavior of hte weighting matrix. it may not coverge?
#looks like the issue is that GMM gives weight to the bad assumptions?

In [1]:
import numpy as np
from scipy.optimize import minimize

In [2]:
def gen_data(nobs=1000, locy=0,locx=0,scaley=1,scalex=1):
    
    #error terms
    y = np.random.normal(loc=locy, scale=scaley, size=(nobs,1))
    x = np.random.normal(loc=locx, scale=scalex, size=(nobs,1))

    return y,x,nobs

#the simplest example is mu = avg(x) and mu = avg(y)? only one can be true?

In [17]:
def compute_moments(params,y,x,v=False):
    mu = np.ones(y.shape).dot([params])
    g=  np.concatenate( (y-mu,x-mu), axis=1)
    if v:
        print(g)
    return g

def gmm_obj(params,y,x,weights=None):
    g = compute_moments(params,y,x)
    if weights is not None:
        weights = np.linalg.inv(weights)
    if weights is None:
        weights = np.eye(g.shape[1])
    g = g.mean(axis=0)
    return g.dot(weights).dot(g)

def test_run(y,x):
    res = minimize( gmm_obj, [1],  args=(y,x))
    print(res.x)
    weights =  np.cov(compute_moments(res.x,y,x),rowvar=False)
    print(weights)
    print('-- iter2 --')
    res = minimize( gmm_obj, [1],  args=(y,x,weights))
    print(res.x)
    weights =  np.cov(compute_moments(res.x,y,x),rowvar=False)
    print(weights)
    print('=============')


y,x,nobs = gen_data()
test_run(y,x)

y,x,nobs = gen_data(locy=1,locx=0,scaley=1,scalex=1)
test_run(y,x)

y,x,nobs = gen_data(locy=1,locx=0,scaley=3,scalex=1)
test_run(y,x)

y,x,nobs = gen_data(locy=1,locx=0,scaley=1,scalex=3)
test_run(y,x)

#in this situation, the covariance matrix doesn't actually depend on the parameters...

[0.00673409]
[[ 0.97746115 -0.04882105]
 [-0.04882105  1.04003912]]
-- iter2 --
[0.00667486]
[[ 0.97746115 -0.04882105]
 [-0.04882105  1.04003912]]
[0.50560577]
[[ 0.96257557 -0.00505014]
 [-0.00505014  0.96476155]]
-- iter2 --
[0.50613884]
[[ 0.96257557 -0.00505014]
 [-0.00505014  0.96476155]]
[0.46044766]
[[8.72756511 0.18952145]
 [0.18952145 0.99383245]]
-- iter2 --
[0.07304351]
[[8.72756511 0.18952145]
 [0.18952145 0.99383245]]
[0.50574814]
[[ 1.0538563  -0.02474323]
 [-0.02474323  9.18327262]]
-- iter2 --
[0.90410428]
[[ 1.0538563  -0.02474323]
 [-0.02474323  9.18327262]]
